### PR TITLE
Issue 317: Add support for jakarta.mail packages

### PR DESCRIPTION
**Pull request by uberskigeek**
These changes pass all the tests when running man clean install -Pdocker. Additional testing may be required. This is an initial effort to move to the jakarta.mail package names.

### CODE REVIEW

**Comment by marcelmay** [comment]
Thx alot, @uberskigeek . 

I will have a look at this at the weekend. That's a big PR.

Some thoughts open for discussion:
- Would it be a better to first go for Jakarta Mail 1.6.5 <-> GreenMail 1.6.x (and later for Jakarta Mail 2.x). Haven't looked at 2.x release candidates and the [changes](https://jakarta.ee/specifications/mail/2.0/mail-spec-2.0-RC6.html) involved.

**Comment by uberskigeek** [comment]
I'm not sure what the best path is. The Jakarta EE changes are breaking changes. So I would think a Java EE and a JakartaEE version of the server would need to be maintained separately. Not sure how you'd like to go about doing this, Separate branches for each version??

**Comment by uberskigeek** [comment]
Tried to merge with master.. some issues encountered closing the pull and restarting...

**Comment by marcelmay** [comment]
@uberskigeek , I'd be very interested for a PR for [jakarta.mail 1.6.5 ](https://projects.eclipse.org/projects/ee4j.mail) for next GreenMail 1.6 version.

**Pull request closed without merging**
