### PR TITLE
Update to jakarta.mail-api 2.1.0

### PR DESCRIPTION
**Pull request by adamretter**
This updates to jakarta mail api 2.1.0 and Eclipse Angus as the new API implementation.

However this is not yet working... see https://github.com/eclipse-ee4j/angus-mail/issues/37

### CODE REVIEW

**Comment by adamretter** [comment]
The upshot is that this change requires Java 11 at runtime.

@marcelmay are there any plans to move to Java 11?

**Comment by marcelmay** [comment]
Sorry @adamretter for the late reply.

I will roll a 2.x alpha 3 in the next few days, and then make Java 11  a requirement for GreenMail 2.x .

**Review by mabartos — COMMENTED** [review]
Hello @adamretter! What's the current progress on this? :))

**Comment by adamretter** [comment]
@mabartos No progress on my part. Is something needed?

**Comment by adamretter** [comment]
@mabartos I have now updated this for Eclipse Angus Mail 2.0.1 with is the Jakarta EE implementation of Jakarta Mail. However I am now seeing a couple of failing tests like:

```
Caused by: java.io.IOException: Can't verify identity of server: 127.0.0.1
	at org.eclipse.angus.mail.util.SocketFetcher.checkServerIdentity(SocketFetcher.java:699)
	at org.eclipse.angus.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:636)
	at org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:402)
	at org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:215)
	at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2208)
```

I am not sure how GreenMail sets up its SSL identity for the host... any pointers?

**Comment by mabartos** [comment]
@adamretter Have you tried to execute these tests even before the upgrade? AFAIK, it's not possible to execute tests with TLS on a local machine. As in the code, there are no certs or other stuff required for the TLS establishment.

**Comment by adamretter** [comment]
@mabartos Running `mvn clean verify` on `master` seems to show that all tests pass (before my changes).

**Comment by marcelmay** [comment]
@adamretter , @mabartos - I can have a look on the SSL issue this weekend.
GreenMail uses [tweaks](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/util/DummySSLSocketFactory.java) for local secure connections.

**Comment by marcelmay** [comment]
It seems Angus Mail enables `mail.<PROTOCOL>.ssl.checkserveridentity` by default :
https://github.com/eclipse-ee4j/angus-mail/issues/12

This breaks with JavaMail, as the default was always false:
From https://jakarta.ee/specifications/mail/1.6/apidocs/com/sun/mail/smtp/package-summary.html :

>  mail.smtp.ssl.checkserveridentity	boolean	If set to true, check the server identity as specified by [RFC 2595](http://www.ietf.org/rfc/rfc2595.txt). These additional checks based on the content of the server's certificate are intended to prevent man-in-the-middle attacks. **Defaults to false.**

To fix this, you'll need to set the property to `false` in GreenMail [ServerSetup.java](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/util/ServerSetup.java#L248)

```
        if (isSecure()) {
            ....
            // Required for Angus Mail
            props.setProperty(MAIL_DOT + getProtocol() + ".ssl.checkserveridentity", "false");
        }
```

**Comment by adamretter** [comment]
@marcelmay Awesome thanks! I have just added that change now :-)

**Comment by adamretter** [comment]
@marcelmay Thanks for kicking off the CI. I just wondered if you perhaps yet had any idea of a timeline for this change to be included and released in a version of GreenMail?

**Comment by marcelmay** [comment]
I hope to roll 2.0 this weekend, and would also do an initial 2.1 "alpha" (=2.0 + this PR) then.

**Comment by marcelmay** [comment]
GreenMail 2.0 is out, will do 2.1.0-alpha-1 including this PR next at the beginning of this week.

**Pull request merged**
