### PR TITLE
Resolves #99

### LINKED ISSUE #99: Modify GreenMailUtil to remove all emails
As mentioned in issue #62 it would be nice to have a utility method to remove all emails from active message stores.

### PR DESCRIPTION
**Pull request by buildscientist**
Added a method in GreenMailUtil to handle removal of all emails regardless of serversetup (IMAP or POP3).

### CODE REVIEW

**Comment by buildscientist** [comment]
@marcelmay please code review and accept this change if you don't mind :+1: 

Thanks.

**Comment by marcelmay** [comment]
Good work!

What about adding GreenMailUtil.purgeEmailFromAllMailboxes() directly to GreenMail?

**Comment by buildscientist** [comment]
@marcelmay Sure I can do that. So you're suggesting implementing the method directly in GreenMail instead of in the GreenMailUtil class?

**Comment by marcelmay** [comment]
Yes, I think it better fits here

**Comment by buildscientist** [comment]
@marcelmay so I looked at the GreenMail class and it seems to me that this utility method would be better off in GreenMailUtils. The purpose of GreenMail (I'm referring to single responsibility principle in OO development) seems to be for setup/teardown of GreenMail related services, users etc. 

It also acts as an wrapper around service specific functionality - getting received messages, setting users, quotas etc.
 
Users can always call GreenMail.util to get an instance of the GreenMailUtil. As an aside I'm not quite clear as to why GreenMailUtil is implemented as a singleton. 

Given that GreenMailUtil is approaching 500 LOC we might want to consider refactoring it down to purpose specific static utility classes - e.g. user management, MimeMessage handlers. 

That said I'm open to handling this either way.

**Comment by marcelmay** [comment]
GreenMailUtil is a helper and should be the last choice to add things.
Speaking OO, it violates the "Single responsibility principle".

GreenMail class is representing the overall server(s) - basically a container for the protocol handlers.
So when you want to delete a mail box for all, it is the best fit.

**Comment by buildscientist** [comment]
@marcelmay made changes as requested - please code review and pull into master. Thanks :)

**Comment by marcelmay** [comment]
Looks good!

Some remarks:
- You do not have to modify GreenMailRule, it is a GreenMail instance already. See ImapServerTest for using GreenMailRule and accessing GreenMail. Simplifies your ExamplePurgeAllEmailsTest, too (no setup etc.).
- GreenMailUtil.java and GreenMailUtilTest should not be included, nothing changed except for imports. Contains new unused imports.
- You do not need two tests for both IMAP and POP3, it is one mailbox underneath.

**Comment by marcelmay** [comment]
I tried to autolink the pull request to issue ... seems not to work via pull request name.

**Comment by buildscientist** [comment]
@marcelmay ping for another (and hopefully final) code review.

**Pull request merged**
