### PR TITLE
Increases the time to wait for all services to start

### PR DESCRIPTION
**Pull request by clboettcher**
Hey,

this PR increases the total time that com.icegreen.greenmail.util.GreenMail#start waits on isRunning()==true for all services before a RuntimeException is thrown to 10 seconds (was: 1 second).

Background is that I have a test that starts imaps and smtps which takes roughly 1 second. With the old timeout this test would fail sometimes on a slower machine. 

This is a copy of https://github.com/camann9/greenmail/pull/1, does camann9 still work on the project?

Regards, Claudius

### CODE REVIEW

**Comment by buildscientist** [comment]
@clboettcher Please merge the latest code from master into your fork. The CI build failed because you're running older code. 

Yes @camann9 is still part of the GreenMail but @marcelmay and I are primarily contributing code and managing the project for the time being.

**Comment by marcelmay** [comment]
Hi @clboettcher,

in #76 we introduced a configurable timeout, which makes your patch probably obsolete.

Can you check latest SNAPSHOT if it works for you?
It is deployed as1.4.2-SNAPSHOT to the [maven snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/).

**Comment by buildscientist** [comment]
@marcelmay Good catch - completely forgot you introduced that feature.

**Comment by marcelmay** [comment]
Hi @clboettcher , have you tried latest snapshot if it configuring works for you? Otherwise I'll close the pull request. Thx!

**Comment by clboettcher** [comment]
Hi @marcelmay and @buildscientist, I'm sorry that i did not reply earlier. I got notified on a wrong email address -.-.

Thanks for the hint on #76. This is exactly what i need! Do you have a rough schedule for releasing 1.4.2?

**Comment by marcelmay** [comment]
Hi @clboettcher ,

we plan to skip 1.4.2 and do a release 1.5 around the end of february.

You can try [1.4.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen) meanwhile...

**Pull request closed without merging**
