### PR TITLE
Issue 102

### LINKED ISSUE #102: Setup parallel builds on CircleCI
CircleCI currently provides us 4 build executors but we're not taking advantage of build parallelization. 

Modify the CircleCI config to build Greenmail using one version of the JDK per build executor.

### PR DESCRIPTION
**Pull request by buildscientist**
This resolves #102.

### CODE REVIEW

**Comment by buildscientist** [comment]
Hi @marcelmay - can you review and pull in the PR? Thanks. 

The good news is that by parallelizing the build we've cut down our build time in half from 6 to 3 minutes! :+1:

**Comment by marcelmay** [comment]
Hi Youssef,

that is really great news!

As there were a lot of commits (12), can you include the issue number in the commit msg?
Github then auto-references your commit in the related issue (or even closes the issue automatically).

Easiest way is probably to squash them to a combined msg with the number and the issue topic:
“Issue #102 : Setup parallel builds on CircleCI”
or to close issue when pulling:
“Fixes #102: setup parallel builds on CircleCI” 

I’d do it for you, but then I’d be in the history instead of you.

Cheers,
Marcel

**Comment by buildscientist** [comment]
@marcelmay 

I'm not a huge fan of squashing commits because the commit log shows the progression of changes - e.g. how the developer came to make those changes. To me a commit log is a story. 

That said since this is just a change related to CircleCI I've squashed all 12 commits into one.

**Comment by marcelmay** [comment]
Thanks @buildscientist, I totally agree but it is the easiest way to get the issue as part of the messages...?

**Pull request merged**
