### PR TITLE
Gives POP same behaviour as IMAP when using -Dgreenmail.auth.disabled…

### PR DESCRIPTION
**Pull request by davidnewcomb**
`-Dgreenmail.auth.disabled` should work for both protocols. #268

### CODE REVIEW

**Comment by davidnewcomb** [comment]
I ran the tests (in greenmail-core) and they all still passed so yay! ...but at the same time naughty!
I could probably write some unit tests but I'm not going to unless the changes are accepted.

**Comment by marcelmay** [comment]
@davidnewcomb , thx alot. Test would be nice.  I plan to release 1.5.13 this weekend.

**Comment by marcelmay** [comment]
@davidnewcomb , can you rebase your branch from master, and change PR against master?

Thx alot,
Marcel

**Comment by davidnewcomb** [comment]
See PR #311

**Comment by marcelmay** [comment]
Closing as merged by #311 to master.

Thx alot, @davidnewcomb !

**Pull request closed without merging**
