### PR TITLE
Remove junit dependency and move GreenMailRule to test

### PR DESCRIPTION
**Pull request by alexsuter**
Have a look here: https://github.com/greenmail-mail-test/greenmail/issues/225

### CODE REVIEW

**Comment by alexsuter** [comment]
The GreenMailRule is a nice thing, but I think it is not a good idea to depend on a certain JUnit version. I recommend to remove the JUnit dependency and also remove the GreenMailRule feature. A GreenMail library user don't want to depent on the same junit version as GreenMail provides.

What do you think about that?

**Comment by marcelmay** [comment]
This breaks backward compatibility.

I agree it would be nice to decouple JUnit dependency from GreenMail Core (compile scope), though - to be more flexible with different JUnit versions or TestNG.

Moving rule to test scope (with deployment of test JAR) as you propose has most likely the least impact and "pain".

Might be considered for 1.6.x or 2.x.

Thx!

**Comment by PascalSchumacher** [comment]
I'm a `GreenMailRule` user, please do not remove it.

Just make the JUnit dependency optional (add `<optional>true</optional>`). This removes the dependency by default. Users of `GreenMailRule` will have JUnit on the classpath anyway.

**Comment by Yevhensh** [comment]
haha

**Pull request closed without merging**
